// Generated by scripts/shotlib/presentation.py (scripts/build-move.py --video-spec); do not edit.
// One analysis composition per encyclopedia move (moves/<id>/move.json) with a saved trace, contact checks and presentation.
import type { AnalysisSpec } from "../src/model/analysis.ts";
import type { AnalysisTrace, ContactChecks } from "./AnalysisVideo.tsx";
import m_hjerpefinte_trace from "../data/traces/hjerpefinte.trace.json" with { type: "json" };
import m_hjerpefinte_checks from "../shots/hjerpefinte/checks.json" with { type: "json" };
import m_hjerpefinte_spec from "../data/presentations/hjerpefinte.analysis.json" with { type: "json" };

export interface EncyclopediaEntry {
  id: string;
  spec: AnalysisSpec;
  trace: AnalysisTrace;
  checks: ContactChecks;
  text: { kicker: string; title: string; subtitle: string; bug: string; endTitle: string; endSteps: string[] };
}

export const ENCYCLOPEDIA: EncyclopediaEntry[] = [
  { id: "hjerpefinte", spec: m_hjerpefinte_spec as unknown as AnalysisSpec, trace: m_hjerpefinte_trace as unknown as AnalysisTrace, checks: m_hjerpefinte_checks, text: {"kicker": "SHOT ENCYCLOPEDIA", "title": "HJERPEFINTE", "subtitle": "Table hockey · centre feint · designed from the NTHF description", "bug": "HJERPEFINTE", "endTitle": "HJERPEFINTE", "endSteps": ["PUCK OUT ON THE BLADE", "GOALIE EXPECTS THE HJERPE", "PUSH SHOT, RIGHT CORNER"]} },
];
