// Iteration 23: records the versions of the scene the shot renders (geometry version and SHA-256 of the asset
// files the trace's asset_refs name, plus the scene GLB). The Remotion composition compares the trace against
// this manifest and refuses to render on any mismatch; the browser also hashes the GLB it actually loads.
//
//   node scripts/shot23-manifest.ts      (run by `npm run remotion:assets`)
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";

const sha = (p: string): string => createHash("sha256").update(readFileSync(p)).digest("hex");
const geometry = JSON.parse(readFileSync("data/geometry.json", "utf8"));

// Same files as scripts/shot22-trace.py writes into trace.asset_refs.
export const ASSET_FILES: Record<string, string> = {
  figure_molds_sha256: "data/figure-molds.json",
  skater_glb_sha256: "assets/figures/skater_FIN.glb",
  goalie_glb_sha256: "assets/figures/goalie_SWE.glb",
};
const SCENE = "assets/scene/full_static_appearance.glb";
const PUBLIC_SCENE = "public/full_static_appearance.glb";

const scene = sha(SCENE);
if (sha(PUBLIC_SCENE) !== scene) throw new Error(`${PUBLIC_SCENE} differs from ${SCENE}: run npm run remotion:assets`);
const manifest = {
  note: "generated by scripts/shot23-manifest.ts; do not edit",
  geometry_version: geometry.geometry_version,
  asset_sha256: Object.fromEntries(Object.entries(ASSET_FILES).map(([k, p]) => [k, sha(p)])),
  asset_files: ASSET_FILES,
  scene_glb: { path: PUBLIC_SCENE, source: SCENE, sha256: scene },
};
writeFileSync("remotion/asset-manifest.json", JSON.stringify(manifest, null, 1) + "\n");
console.log("wrote remotion/asset-manifest.json", manifest.geometry_version, Object.keys(manifest.asset_sha256).join(", "));
